name: Generate MrNossiom metrics

on:
  schedule: [{ cron: '0 0 */1 * *' }]
  workflow_dispatch:
  push:

jobs:
  generate_metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate bio metrics
        uses: lowlighter/metrics@v3.19
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics/bio.svg
          config_timezone: Europe/Paris

          base: header, activity, community, repositories, metadata

      - name: Generate code metrics
        uses: lowlighter/metrics@v3.19
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics/code.svg
          config_order: notable, stars, wakatime, code
          config_timezone: Europe/Paris

          # Show stats on large projects I contributed to
          plugin_notable: true
          plugin_notable_filter: stars:>500
          plugin_notable_repositories: true
          plugin_notable_from: all

          # Shows latest starred repositories
          plugin_stars: true
          plugin_stars_limit: 3

          # WakaTime tracking
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 4

          # Display a snippet of random code I wrote
          plugin_code: true
          plugin_code_lines: 20
          plugin_code_load: 400
          plugin_code_languages: javascript, typescript

      - name: Generate social metrics
        uses: lowlighter/metrics@v3.19
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics/socials.svg
          config_order: discussions, stargazers, music, topics, people, sponsors

          # Display discussion (issues, PRs)
          plugin_discussions: true

          # Stargazers graph
          plugin_stargazers: true

          # Spotify tracking
          plugin_music: true
          plugin_music_provider: spotify
          plugin_music_mode: top
          plugin_music_top_type: tracks
          plugin_music_time_range: short
          plugin_music_limit: 4
          plugin_music_token: '${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}'
          plugin_music_played_at: true

          # Display follow topics in GitHub
          plugin_topics: true
          plugin_topics_limit: 0
          plugin_topics_mode: icons

          # Display followers
          plugin_people: true
          plugin_people_types: sponsors, followers
          plugin_people_shuffle: true

          # Display sponsors (hidden)
          plugin_sponsors: false
          plugin_sponsors_sections: goal, about
