name: Generate MrNossiom metrics

on:
  schedule: [{ cron: '0 0 */1 * *' }]
  workflow_dispatch:
  push:

jobs:
  generate_metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugins_errors_fatal: true

          # Show stats on recent languages I used
          plugin_languages: true
          plugin_languages_threshold: 2%
          plugin_languages_details: percentage
          plugin_languages_sections: recently-used

          # Shows recent activity
          plugin_activity: true
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: all

          # Show stats on recent projects I contributed to
          plugin_notable: true
          plugin_notable_filter: stars:>500
          plugin_notable_repositories: true
          plugin_notable_from: all

          # Shows latest starred repositories
          plugin_stars: true
          plugin_stars_limit: 3

          # Display a snippet of random code I wrote
          plugin_code: true
          plugin_code_lines: 12
          plugin_code_load: 100
          plugin_code_visibility: private,public

          # WakaTime tracking
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 4

          # Display sponsors (displayed)
          plugin_sponsors: false
          plugin_sponsors_sections: goal, about

          # Spotify tracking
          plugin_music: true
          plugin_music_provider: spotify
          plugin_music_mode: top
          plugin_music_top_type: tracks
          plugin_music_time_range: short
          plugin_music_limit: 4
          plugin_music_token: '${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}'
          plugin_music_played_at: true
