name: Generate profile metrics

on:
  schedule: [{ cron: '0 0 */1 * *' }]
  workflow_dispatch:
  push:

jobs:
  generate_metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: a6a60000aa7170b2ea668e138dabc107
          filename: metrics.svg

          config_order: notable, rss, stargazers, people
          config_timezone: Europe/Paris

          # Show stats on large projects I contributed to
          plugin_notable: true
          plugin_notable_filter: stars:>500
          plugin_notable_repositories: true
          plugin_notable_from: all

          # Display 3 last entries of an RSS feed
          plugin_rss: true
          plugin_rss_source: https://wiro.world/atom.xml
          plugin_rss_limit: 3

          # Stargazers graph
          plugin_stargazers: true

          # Display followers
          plugin_people: true
          plugin_people_types: sponsors, followers
          plugin_people_shuffle: true
